name: Deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        if: ${{ !env.ACT }}

      - name: Update CHANGELOG
        if: ${{ !env.ACT }}
        id: changelog
        uses: ./
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        if: ${{ !env.ACT }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Commit CHANGELOG.md
        if: ${{ !env.ACT }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md

      # LOCAL TEST

      - name: (local) Checkout Code
        uses: actions/checkout@v2
        if: ${{ env.ACT }}
        with:
          path: changelog-action

      - name: (local) Update CHANGELOG
        if: ${{ env.ACT }}
        uses: ./
        with:
          token: ${{ github.token }}
          tag: ${{ env.GITHUB_REF_NAME }}
